[project]
name = "logger-display"
version = "1.0.0"
description = "Temperature logger display web server"
dependencies = [
    "flask",
    openmeteo_requests,
    requests_cache,
    retry_requests
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
